### ISSUE TITLE
这个项目是如何 import Alamofire 的？

### ISSUE THREAD

**Issue by SunsetWan** [qiwihui/SMSFilters#1]
你好，请问是用 CocoaPods pod install 吗？还有，在本地运行之前，需要先在 Jupyter Notebook 上训练 model 吗？谢谢

**Comment by qiwihui** [comment]
这个项目使用carthage管理，不是cocoapod。

`carthage update --platform ios`

模型已经训练好加在项目中了，不用重新训练。如果要变模型的话可以自己训练。

**Comment by qiwihui** [comment]
这个项目是实验性的，模型不准确，不要用于生产。

**Comment by SunsetWan** [comment]
> 这个项目是实验性的，模型不准确，不要用于生产。

谢谢，明白，我也是用来模仿学习的。

**Comment by SunsetWan** [comment]
> 这个项目使用carthage管理，不是cocoapod。
> 
> `carthage update --platform ios`
> 
> 模型已经训练好加在项目中了，不用重新训练。如果要变模型的话可以自己训练。

还有一个，你使用的 Alamofire 的版本是：大于 4.2.0 的吗？谢谢

**Comment by SunsetWan** [comment]
> > 这个项目使用carthage管理，不是cocoapod。
> > `carthage update --platform ios`
> > 模型已经训练好加在项目中了，不用重新训练。如果要变模型的话可以自己训练。
> 
> 还有一个，你使用的 Alamofire 的版本是：大于 4.2.0 的吗？谢谢

我已经在 Cartfile 里看到了，是 4.0。谢谢
